version: '3.8'

services:

  zookeeper:
      image: confluentinc/cp-zookeeper:latest
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT 
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Nour@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "1433"
    ports:
      - "1433:1433"

  StudentAPI:
    image: studentapi
    build:
      context: ./Service1/StudentAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092

  AdminAPI:
    image: adminapi
    build:
      context: ./Service2/AdminAPI
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
      

 